services:
  db:
    image: postgres:17-alpine
    container_name: smart_task_db
    restart: always
    environment:
      - POSTGRES_USER=smart_user
      - POSTGRES_PASSWORD=smart_pass
      - POSTGRES_DB=smart_task_hub
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_smart_task.sql:/docker-entrypoint-initdb.d/init_smart_task.sql
    ports:
      - "5433:5432"

  smart_task_copilot:
    image: smart_task_copilot
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 45666:45666
    container_name: smart_task_copilot
    depends_on:
      - db
    environment:
      - MCP_TRANSPORT=http
      - PORT=45666
      - MCP_HOST=0.0.0.0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=smart_task_hub
      - DB_USER=smart_user
      - DB_PASSWORD=smart_pass
    restart: on-failure

volumes:
  postgres_data:
